# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
jobs:
  - job: Ubuntu
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - script: |
          set -e
        displayName: "Install Services"
      - task: NodeTool@0
        inputs:
          versionSpec: "12.4.0"
        displayName: "Install Node.js"
      - script: |
          npm install
          npm run compile
        displayName: "Run install and compile"
      - script: |
          npm run test
        displayName: "Run Tests"
  - job: MacOS
    pool:
      vmImage: "macos-10.13"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "12.4.0"
        displayName: "Install Node.js"
      - script: |
          npm install
          npm run compile
        displayName: "Run install and compile"
      - script: |
          npm run test
        displayName: "Run Tests"
  - job: Windows
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "12.4.0"
        displayName: "Install Node.js"
      - script: |
          npm install
          npm run compile
        displayName: "Run install and compile"
      - script: |
          npm run test
        displayName: "Run Tests"
